# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    hob.mailer.from: ~
    hob.response.pagination.header: 'X-Pagination-'
    hob.common.jwt.jwtencoder.privateKey: ~
    hob.common.jwt.jwtencoder.publicKey: ~
    hob.common.jwt.jwtencoder.passPhrase: ~
    hob.common.jwt.ttl: 60

services:

#### SERVICES #####

    jms_serializer.array_deserialization_visitor:
            class: HOB\CommonBundle\Serializer\FormDeserializationVisitor
            arguments: [ '@jms_serializer.naming_strategy', '@jms_serializer.object_constructor' ]
            tags:
              - { name: jms_serializer.deserialization_visitor, format: form }

    hob.common.mailer:
        class: HOB\CommonBundle\Mailer\Mailer
        arguments:
            - '@mailer'
            - '@templating'
            - '%hob.mailer.from%'

    hob.common.response.view:
        class: HOB\CommonBundle\Response\ViewResponse
        arguments: ['@hob.common.pagination']

    hob.common.pagination:
        class: HOB\CommonBundle\Pagination\Pagination
        arguments: ['%hob.response.pagination.header%', '@router']

    hob.common.jwt.jwtencoder:
        class: HOB\CommonBundle\JWT\Encoder\JWTEncoder
        arguments: ['%hob.common.jwt.jwtencoder.privateKey%','%hob.common.jwt.jwtencoder.publicKey%','%hob.common.jwt.jwtencoder.passPhrase%']

    hob.common.jwt.manager:
        class: HOB\CommonBundle\JWT\JWTManager
        arguments: ['@hob.common.jwt.jwtencoder', '%hob.common.jwt.ttl%']
